wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/hyprpaper.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/hyprpaper.png
    fit_mode = cover
}
splash = false
