-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = true,
            size = 1,
        },
        dim_special = 0.35,
        rounding = 16,
        rounding_power = 2.0,
    },
    general = {
        gaps_in = 5,
    },
    misc = {
        vrr = 3,
    },
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    mode = "1280x720@60.05Hz",
    position = "1920x360",
    scale = 1,
    cm = "srgb",
})

-- Workspaces
hl.workspace_rule({
    workspace = 10,
    monitor = "eDP-1",
})
hl.workspace_rule({
    workspace = 3,
    monitor = "HDMI-A-1",
})

-- Keybinds
hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.exec_cmd("zen"))
