$mainMod = ALT
$terminal = kitty
$browser = zen
$notes = obsidian
$fileManager = nautilus
$menu = wofi

bind = $mainMod, V, exec, ~/.config/wofi/wofi-cliphist.sh
bind = $mainMod, R, exec, wofi --show run
bind = $mainMod, T, exec, $terminal
bind = $mainMod, B, exec, $browser
bind = $mainMod, O, exec, $notes
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, A, exec, $menu

bind = SUPER, B, exec, zen
bind = SUPER, V, exec, wofi-copy menu

bind = $mainMod, Q, killactive
bind = $mainMod, M, exit
bind = $mainMod, W, togglefloating

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bind = $mainMod, S, exec, grimblast --notify copy area
bind = , Print, exec, grimblast --notify copy area
bind = $mainMod, Print, exec, grimblast --notify copysave active
bind = $mainMod ALT, Print, exec, grimblast --notify copysave area
bind = $mainMod SHIFT, S, exec, grimblast --notify copy output

bind = CTRL, Escape, exec, killall waybar || waybar
