general {
    gaps_in = 5
    gaps_out = 5
    border_size = 2
    col.active_border = rgb(6E6E6E)
    col.inactive_border = rgb(333333)
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 16
    rounding_power = 2.0
    active_opacity = 1.0
    inactive_opacity = 1.0
    dim_special = 0.35

    blur {
        enabled = true
        size = 1
        passes = 0
        new_optimizations = true
        vibrancy = 0.1696
        ignore_opacity = true
    }
}

animations {
    enabled = true

    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1

    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 5, winOut, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, loop
    animation = fade, 1, 10, default
    animation = workspaces, 1, 5, wind
}

dwindle {
    preserve_split = true
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = false
    disable_splash_rendering = true
    vrr = 1
}
